namespace EmergencyVR.Medical
{
    public enum DialogueIntent
    {
        GREETING, MAIN_SYMPTOM, SYMPTOM_DESCRIPTION, ONSET, LOSS_OF_CONSCIOUSNESS,
        CHEST_PAIN, BREATHING_DIFFICULTY, PALPITATIONS, CARDIAC_HISTORY,
        MEDICATION, FOOD_DRINK, CONSENT_HELP, CURRENT_STATUS
    }
}
